service: lambdaService
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-1
  memorySize: 512
plugins:
  - serverless-offline
custom:
  serverless-offline:
    host: 127.0.0.1
    port: 3000
functions:
  hello:
    handler: src/handler.handle
    description: Used as dummy lambda function
    events:
      - http:
          path: /hello-world
          method: get
          cors: true
          response:
            headers:
              Content-Type: "'application/json'"
              Cache-Control: "'max-age=120'"
  test:
    handler: src/handler.test
    description: Test lambda function
    events:
      - http:
        path: /test
        method: get
        cors: true
        response:
          headers:
            Content-Type: "'application/json'"
            Cache-Contro: "'max-age=120'"